Update Template

diff --git a/data/scripts/SystemUpdate b/data/scripts/SystemUpdate
--- a/data/scripts/SystemUpdate
+++ b/data/scripts/SystemUpdate
@@ -1,328 +1,224 @@
 #!/bin/bash
-GetScriptDir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
-GetScriptName=$(basename "${BASH_SOURCE[0]}")
+SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
+SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}")"
 
-# It will find the supported packages and enable them.
-# In case "false" is set, you have to enable it manually one by one.
-auto=false
+declare -A COLORS=(
+    [Black]='\033[0;30m' [DarkBlue]='\033[0;34m' [DarkGreen]='\033[0;32m' [DarkCyan]='\033[0;36m'
+    [DarkRed]='\033[0;31m' [DarkMagenta]='\033[0;35m' [DarkYellow]='\033[0;33m' [Gray]='\033[0;37m'
+    [DarkGray]='\033[1;30m' [Blue]='\033[1;34m' [Green]='\033[1;32m' [Cyan]='\033[1;36m'
+    [Red]='\033[1;31m' [Magenta]='\033[1;35m' [Yellow]='\033[1;33m' [White]='\033[1;37m'
+    [NoColor]='\033[0m'
+)
 
-# If you want to enable it manually,
-# remove the "#" from the relevant packages.
 
-zypper=true
-# dnf=false
-# apt=false
-brew=true
-flatpak=true
-snap=true
-
-AllYes=false
-# ---------------------
-
-Black='\033[0;30m'
-DarkBlue='\033[0;34m'
-DarkGreen='\033[0;32m'
-DarkCyan='\033[0;36m'
-DarkRed='\033[0;31m'
-DarkMagenta='\033[0;35m'
-DarkYellow='\033[0;33m'
-Gray='\033[0;37m'
-DarkGray='\033[1;30m'
-Blue='\033[1;34m'
-Green='\033[1;32m'
-Cyan='\033[1;36m'
-Red='\033[1;31m'
-Magenta='\033[1;35m'
-Yellow='\033[1;33m'
-White='\033[1;37m'
-NoColor='\033[0m' # No Color
-
-USER_PASSWORD=""
-function rootpassword {
-if [[ $EUID -eq 0 ]]; then
-     echo -e "${Red}You must not be Super User/Root.${NoColor}"
-   exit 1
+if [[ "$(uname -s)" != "Linux" ]]; then
+    echo -e "${COLORS[Red]}This script is designed for Linux.${COLORS[NoColor]}"
+    exit 1
 fi
-sudo --reset-timestamp
-# shellcheck disable=SC2162
-echo -n -e "${Cyan}Password for ${Red}root:${NoColor} "
-# shellcheck disable=SC2162
-read -s USER_PASSWORD
-echo -e "\n${Yellow}Password checking...${NoColor}"
-if echo "$USER_PASSWORD" | sudo -S true >/dev/null 2>&1; then
-    echo -e "${Green}Password verified.${NoColor}\n"
-    function SUDO {
-        # shellcheck disable=SC2317
-        echo "$USER_PASSWORD" | sudo -S "$@"
-    }
-else
-    echo -e "${Red}Password could not be verified ${NoColor}\n"
-    rootpassword
-fi  
+
+function is_command() { command -v "$1" &>/dev/null; }
+
+function check_root() {
+    if [[ $EUID -eq 0 ]]; then
+        echo -e "${COLORS[Red]}You must not run this script as root.${COLORS[NoColor]}"
+        exit 1
+    fi
 }
-function rootpassword_end {
-    unset USER_PASSWORD
+
+function verify_password() {
+    echo -n -e "${COLORS[Cyan]}Password for ${COLORS[Red]}root:${COLORS[NoColor]} "
+    read -s user_password
+    echo -e "\n${COLORS[Yellow]}Verifying password...${COLORS[NoColor]}"
+    echo "$user_password" | sudo -S true &>/dev/null && return 0 || {
+        echo -e "${COLORS[Red]}Incorrect password.${COLORS[NoColor]}"
+        exit 1
+    }
+}
+
+function SUDO() {
+    echo "$user_password" | sudo -S "$@"
+}
+
+function cleanup() {
+    unset user_password
     sudo --reset-timestamp
 }
+trap cleanup EXIT
 
-function InternetCheck {
- curl -s --head http://www.google.com | grep "200" > /dev/null
-    if [ $? -ne 0 ]; then
-        echo -e "${Red}You do not have an Internet Connection.${NoColor}"
+function check_internet() {
+    curl -s --head http://www.google.com | grep "200" &>/dev/null || {
+        echo -e "${COLORS[Red]}No Internet connection.${COLORS[NoColor]}"
         exit 1
-    fi   
-}
-function Flatpak_SysUpdate {
-    InternetCheck
-    Yes=$1
-    if [[ $Yes = "yes" || $Yes = "-y"  || $Yes = "true" ]]; then
-        Yes="-y"
-    else
-        Yes=""
-    fi
-
-    PackagePrep="flatpak"
-    Package="$PackagePrep"
-    PackageUpdate="upgrade $Yes"
-
-    SUDO su -c "$Package $PackageUpdate"
+    }
 }
 
-function Snapd_SysUpdate {
-InternetCheck
-    PackagePrep="snap"
-    Package="$PackagePrep"
-    PackageUpdate="update"
+. /etc/os-release
+DISTRO=$(echo "$NAME" | tr '[:upper:]' '[:lower:]')
 
-    SUDO su -c "$Package $PackageUpdate"
-
+function get_package_manager() {
+    case "$DISTRO" in
+    *"opensuse tumbleweed"*) echo "zypper" ;;
+    *"fedora"*) echo "dnf" ;;
+    *"debian"* | *"ubuntu"*) echo "apt" ;;
+    *) echo "unsupported" ;;
+    esac
 }
 
-function Homebrew_SysUpdate {
-    InternetCheck
-    if [ -f "/home/linuxbrew/.linuxbrew/bin/brew" ]; then
-        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
-        PackagePrep="brew"
-        Package="$PackagePrep"
-        PackageUpdate="upgrade"
-        PackageRefresh="update"
-
-        sh -c "$Package $PackageRefresh && $Package $PackageUpdate"
-    fi
+PACKAGE_MANAGER=$(get_package_manager)
+[[ "$PACKAGE_MANAGER" == "unsupported" ]] && {
+    echo -e "${COLORS[Red]}Unsupported Linux distribution.${COLORS[NoColor]}"
+    exit 1
 }
 
-function Debian_SysUpdate {
-# APT
-    InternetCheck
-        Yes=$1
-    if [[ $Yes = "yes" || $Yes = "-y"  || $Yes = "true" ]]; then
-        Yes="-y"
-    else
-        Yes=""
-    fi
-    PackagePrep="apt"
-    Package="$PackagePrep"
-    PackageUpdate="upgrade --allow-unauthenticated $Yes"
-    PackageRefresh="update"
+CONF_FILE="$HOME/.config/systemupdate.conf"
+declare -A DEFAULTS=(
+    [Flatpak]=$(is_command flatpak && echo true || echo false)
+    [Snap]=$(is_command snap && echo true || echo false)
+    [brew]=$(is_command brew && echo true || echo false)
+    [Package]=$PACKAGE_MANAGER
+    [AllYes]=true
+)
 
-    SUDO su -c "$Package $PackageRefresh && $Package $PackageUpdate"
-}
-
-function Fedora_SysUpdate {
-# DNF
-    InternetCheck
-        Yes=$1
-        Rolling=$2
-    if [[ $Yes = "yes" || $Yes = "-y"  || $Yes = "true" ]]; then
-        Yes="-y"
-    else
-        Yes=""
-    fi
-    if [[ $Rolling = "yes" || $Rolling = "-y"  || $Rolling = "true" ]]; then
-        Rolling="distro-sync"
-    else
-        Rolling="update"
-    fi
-    
-    PackagePrep="dnf"
-    Package="$PackagePrep"
-    PackageUpdate="$Rolling --nogpgcheck $Yes"
-    PackageRefresh="makecache"
-
-    SUDO su -c "$Package $PackageRefresh && $Package $PackageUpdate"
-}
-
-function Opensuse_SysUpdate {
-# ZYPPER
-    InternetCheck
-        Yes=$1
-        Rolling=$2
-    if [[ $Yes = "yes" || $Yes = "-y"  || $Yes = "true" ]]; then
-        Yes="-y"
-    else
-        Yes=""
-    fi
-    if [[ $Rolling = "yes" || $Rolling = "-y"  || $Rolling = "true" ]]; then
-        Rolling="dup"
-    else
-        Rolling="up"
-    fi
-    
-    PackagePrep="zypper"
-    Package="$PackagePrep --gpg-auto-import-keys"
-    PackageUpdate="$Rolling --details -l $Yes"
-    PackageRefresh="ref"
-
-    SUDO su -c "$Package $PackageRefresh && $Package $PackageUpdate"
-}
-
-function auto_package {
-    if [ $auto = "true" ]; then
-        if type -P flatpak > /dev/null; then
-            flatpak=true
-        fi
-        if type -P snap > /dev/null; then
-            snap=true
-        fi
-        if type -P brew > /dev/null; then
-            brew=true
-        fi
-        # INTERNAL PACKAGES
-        if type -P apt > /dev/null; then
-            apt=true
-        fi
-        if type -P dnf > /dev/null; then
-            dnf=true
-        fi
-        if type -P zypper > /dev/null; then
-            zypper=true
-        fi
-    fi
-}
-
-function CheckCommand {
-    if type -P $1 > /dev/null; then
-        return 0
-    else
-        return 1
-    fi
-}
-
-
-function package_install {
-    Arg=$1
-    . /etc/os-release
-    DISTRO=$(echo $NAME | tr '[:upper:]' '[:lower:]')
-
-    if [[ $flatpak == "true" ]]; then
-        if CheckCommand flatpak; then
-            Flatpak_SysUpdate $1
-        fi
-    fi
-
-    if [[ $snap == "true" ]]; then
-        if CheckCommand snap; then
-            Snapd_SysUpdate
-        fi
-    fi
-
-    if [[ $brew == "true" ]]; then
-        if CheckCommand brew; then
-            Homebrew_SysUpdate
-        fi
-    fi
-
-    if [[ $apt == "true" ]]; then
-        if CheckCommand apt; then
-            Debian_SysUpdate $1
-        fi
-    fi
-    if [[ $dnf == "true" ]]; then
-        if CheckCommand dnf; then
-            if [[ $DISTRO == *tumbleweed* ]]; then
-                Fedora_SysUpdate $AllYes $1
-            else
-                Fedora_SysUpdate $AllYes $1
-            fi
-        fi
-    fi
-    if [[ $zypper == "true" ]]; then
-        if CheckCommand zypper; then
-            if [[ $DISTRO == *tumbleweed* ]]; then
-                Opensuse_SysUpdate $AllYes $1
-            else
-                Opensuse_SysUpdate $AllYes $1
-            fi
-        fi
-    fi 
-}
+[[ ! -f "$CONF_FILE" ]] && printf "PM_Flatpak=%s\nPM_Snap=%s\nPM_brew=%s\nPM_Package=%s\nPM_AllYes=%s\n" \
+    "${DEFAULTS[Flatpak]}" "${DEFAULTS[Snap]}" "${DEFAULTS[brew]}" "${DEFAULTS[Package]}" "${DEFAULTS[AllYes]}" >"$CONF_FILE"
+source "$CONF_FILE"
 
 function HelpFunction {
-    echo -e "${Yellow}Usage:${NoColor}"
-    echo -e "    ${GetScriptName} [OPTIONS]"
-    echo -e ""
-    echo -e "${Yellow}Options:${NoColor}"
-    echo -e "    --help, -h, help     Display this help message."
-    echo -e "    update               Update the script."
-    echo -e "    apt                  Update APT package manager."
-    echo -e "    dnf                  Update DNF package manager."
-    echo -e "    zypper               Update Zypper package manager."
-    echo -e "    flatpak              Update Flatpak package manager."
-    echo -e "    snap                 Update Snap package manager."
-    echo -e "    brew                 Update Homebrew package manager."
-    echo -e "    yes                  Automatically confirm all package updates."
-    echo -e ""
-    echo -e "${Yellow}Examples:${NoColor}"
-    echo -e "    ${GetScriptName} apt yes"
-    echo -e "    ${GetScriptName} dnf"
-    echo -e "    ${GetScriptName} flatpak"
-    echo -e ""
+    echo -e "${COLORS[Cyan]}Usage:${COLORS[NoColor]}"
+    echo "Usage: ${SCRIPT_NAME} [options]"
+    echo -e "\n${COLORS[Cyan]}Options:${COLORS[NoColor]}"
+    echo -e "  -h, --help               Show this help message"
+    echo -e "  -y, --assumeyes          Assume yes for all prompts"
+    echo -e "  -n, --noassumeyes        If --assumeyes for all prompts, then remove"
+    echo -e "  -ef, --enableflatpak     Enable Flatpak updates"
+    echo -e "  -df, --disableflatpak    Disable Flatpak updates"
+    echo -e "  -es, --enablesnap        Enable Snap updates"
+    echo -e "  -ds, --disablesnap       Disable Snap updates"
+    echo -e "  -ep, --enablepackage     Enable package manager updates"
+    echo -e "  -dp, --disablepackage    Disable package manager updates"
+    echo -e "  update                  Update the script itself"
+    exit 0
 }
 
+for arg in "$@"; do
+    case "${arg,,}" in
+    -h | --help)
+        HelpFunction
+        exit 0
+        ;;
+    update)
+        curl -L https://raw.githubusercontent.com/herrwinfried/myconfig/linux/data/scripts/SystemUpdate -o "$SCRIPT_DIR/SystemUpdate"
+        exit 0
+        ;;
+    -y | --assumeyes) PM_AllYes=true ;;
+    -n | --noassumeyes) PM_AllYes=false ;;
+    -ef | --enableflatpak) PM_Flatpak=true ;;
+    -df | --disableflatpak) PM_Flatpak=false ;;
+    -es | --enablesnap) PM_Snap=true ;;
+    -ds | --disablesnap) PM_Snap=false ;;
+    -eh | --enablebrew) PM_brew=true ;;
+    -dh | --disablebrew) PM_brew=false ;;
+    -ep | --enablepackage) PM_Package=$PACKAGE_MANAGER ;;
+    -dp | --disablepackage) PM_Package=false ;;
+    *) echo -e "${COLORS[Red]}Invalid argument: $arg${COLORS[NoColor]}" ;;
+    esac
+done
 
-if [ $# -ne 0 ]; then
-    AllYes=false
+check_root
+check_internet
+verify_password
 
-    i=1
-    j=$#
-
-    while [ $i -le $j ]; do
-        n=$(echo "$1" | tr '[:upper:]' '[:lower:]')
-
-        if [[ $n == "--help" ]] || [[ $n == "-h" ]] || [[ $n == "help" ]]; then
-            HelpFunction
-            exit 1
-        elif [ "$1" = "update" ]; then
-        curl -L https://raw.githubusercontent.com/herrwinfried/myconfig/linux/dotfiles/scripts/SystemUpdate -o "${GetScriptDir}/SystemUpdate"
-        exit 1
-        elif [[ $n == "apt" ]]; then
-            apt=true
-        elif [[ $n == "dnf" ]]; then
-            dnf=true
-        elif [[ $n == "zypper" ]]; then
-            zypper=true
-        elif [[ $n == "flatpak" ]]; then
-            flatpak=true
-        elif [[ $n == "snap" ]]; then
-            snap=true
-        elif [[ $n == "brew" ]]; then
-            brew=true
-        elif [[ $n == "yes" ]]; then
-            AllYes=true
-
-        else
-        echo -e "${Red}invalid argument $n ${NoColor}"
-        sleep 1
+get_zypper_command() {
+    local distro=$(echo "$NAME $VERSION" | tr '[:upper:]' '[:lower:]')
+    local dup_distros=("tumbleweed" "slowroll" "microos" "kubic")
+    local up_distros=("leap")
+    for dup_distro in "${dup_distros[@]}"; do
+        if [[ $distro == *"$dup_distro"* ]]; then
+            echo "dup"
+            return
         fi
-
-        i=$((i + 1))
-        shift 1
     done
-fi
+    for up_distro in "${up_distros[@]}"; do
+        if [[ $distro == *"$up_distro"* ]]; then
+            echo "up"
+            return
+        fi
+    done
+    echo "up"
+}
 
-rootpassword
-if [[ $zypper != "true" && $dnf != "true"  && $apt != "true" ]] && [[ $brew != "true" && $flatpak != "true"  && $snap != "true" ]]; then
-auto_package
-fi
-package_install $AllYes
-rootpassword_end
+get_dnf_command() {
+    local distro=$(echo "$NAME $VERSION" | tr '[:upper:]' '[:lower:]')
+    local dup_distros=("tumbleweed" "slowroll" "microos" "kubic")
+    local up_distros=("leap")
+    for dup_distro in "${dup_distros[@]}"; do
+        if [[ $distro == *"$dup_distro"* ]]; then
+            echo "distro-sync"
+            return
+        fi
+    done
+    for up_distro in "${up_distros[@]}"; do
+        if [[ $distro == *"$up_distro"* ]]; then
+            echo "upgrade"
+            return
+        fi
+    done
+    echo "upgrade"
+}
+
+update_packages() {
+    local manager=$1
+    local isYes=$2
+    if [[ "$isYes" == true ]]; then
+        isYes="-y"
+    else
+        unset isYes
+    fi
+    local refresh_cmd update_cmd
+    case "$manager" in
+    flatpak)
+        refresh_cmd="echo '.'"
+        update_cmd="flatpak update ${isYes}"
+        ;;
+    snap)
+        refresh_cmd="snap refresh"
+        update_cmd="snap refresh"
+        ;;
+    brew)
+        refresh_cmd="/home/linuxbrew/.linuxbrew/bin/brew update"
+        update_cmd="/home/linuxbrew/.linuxbrew/bin/brew upgrade ${isYes}"
+        ;;
+    zypper)
+        local zypper_cmd=$(get_zypper_command)
+        refresh_cmd="zypper --gpg-auto-import-keys refresh"
+        update_cmd="zypper --gpg-auto-import-keys ${zypper_cmd} --details -l ${isYes}"
+        ;;
+    dnf)
+        local dnf_cmd=$(get_dnf_command)
+        refresh_cmd="dnf makecache"
+        update_cmd="dnf ${dnf_cmd} --nogpgcheck ${isYes}"
+        ;;
+    apt)
+        refresh_cmd="apt update"
+        update_cmd="apt upgrade ${isYes}"
+        ;;
+    *)
+        echo -e "${COLORS[Red]}Invalid package manager: $manager${COLORS[NoColor]}"
+        return
+        ;;
+    esac
+
+    if is_command "$manager"; then
+        echo -e "${COLORS[Green]}Updating $manager...${COLORS[NoColor]}"
+        SUDO su -c "$refresh_cmd && $update_cmd"
+    else
+        echo -e "${COLORS[Red]}$manager not found, skipping.${COLORS[NoColor]}"
+    fi
+}
+
+[[ "$PM_Flatpak" == true ]] && update_packages "flatpak" "${PM_AllYes}"
+[[ "$PM_Snap" == true ]] && update_packages "snap" "${PM_AllYes}"
+[[ "$PM_brew" == true ]] && update_packages "brew" "${PM_AllYes}"
+[[ "$PM_Package" != false ]] && update_packages "$PM_Package" "${PM_AllYes}"
+
+cleanup
